[package]
name = "intents"
version = "0.1.0"
edition = "2024"

[dependencies]
id-arena = "2.2.1"
wa2lsp = { path = "../server/wa2lsp" }
url = "2.5"
tokio = { version = "1", features = ["full"] }
dirs = "6.0.0"